name: AI Test Report Integration (Demo)

on:
    workflow_dispatch:
    
jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-noble  # match @playwright/test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Run Playwright Tests (HTML + JSON)
        run: |
          mkdir -p playwright-report
          npx playwright --version || true
          # Run once; JSON goes to stdout so redirect it to a file.
          npm test > playwright-report/sample_results.json || true

          # Safety net if JSON missing/empty
          if [ ! -s playwright-report/sample_results.json ]; then
            echo '{"status":"no-tests-or-failure","suites":[]}' > playwright-report/sample_results.json
          fi

      - name: Upload Playwright JSON
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sample_results
          path: playwright-report/sample_results.json

      - name: Upload Playwright HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: playwright-report/

  ai-agent:
    needs: e2e
    if: ${{ always() }}  # run even if tests failed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout AI Agent Repository
        uses: actions/checkout@v4
        with:
          repository: azza-sudo/TestInsight-Agent
          path: testinsight

      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: sample_results
          path: testinsight

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install AI Agent Dependencies
        working-directory: testinsight
        run: pip install -r requirements.txt

      - name: Run AI Analysis
        working-directory: testinsight
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "Running TestInsight AI Agent..."
          python main.py sample_results.json

      - name: Upload AI Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-report
          path: testinsight/ai_report.json
