name: AI Test Report Integration (Demo)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-noble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: List discovered tests (sanity)
        run: npx playwright test --list || true

      - name: Run Playwright Tests (HTML + JSON + LOG)
        shell: bash
        run: |
          set -euxo pipefail
          RUNLOG="${{ runner.temp }}/playwright-run.log"
          echo "Playwright CLI: $(npx playwright --version || true)"
          echo "Node: $(node -v)"; echo "npm: $(npm -v)"
          npx playwright test 2>&1 | tee "${RUNLOG}"

          # ✅ Ensure JSON exists and is valid
          JSON="${{ github.workspace }}/reports/sample_results.json"
          test -s "${JSON}"
          node -e "JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'))" "${JSON}"

      - name: Upload Playwright JSON (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sample_results            # <<< keep this name
          path: reports/sample_results.json

      - name: Commit JSON report to repo
        if: ${{ always() && github.event_name != 'pull_request' && startsWith(github.ref, 'refs/heads/') }}
        working-directory: ${{ github.workspace }}
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          CURRENT_BRANCH="${GITHUB_REF#refs/heads/}"
          git checkout "$CURRENT_BRANCH"
          git fetch origin "$CURRENT_BRANCH"
          git merge --ff-only "origin/$CURRENT_BRANCH" || true
          git add reports/sample_results.json
          git commit -m "Update Playwright JSON report for $GITHUB_SHA" || echo "No changes to commit"
          git push origin "HEAD:$CURRENT_BRANCH" || echo "Nothing to push"

  run-agent:
    name: Run TestInsight-Agent main.py on results
    runs-on: ubuntu-latest
    needs: e2e                     # <<< fix: depend on the e2e job
    if: ${{ always() }}

    steps:
      - name: Checkout TestInsight-Agent
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/TestInsight-Agent
          path: TestInsight-Agent
          # token: ${{ secrets.PAT_FOR_CROSS_REPO }}  # if needed for private/cross-org

      - name: Download test report artifact
        uses: actions/download-artifact@v4
        with:
          name: sample_results       # <<< match the upload name
          path: artifacts

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install agent dependencies (if any)
        working-directory: TestInsight-Agent
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run TestInsight-Agent on Playwright JSON
        working-directory: TestInsight-Agent
        env:
          REPORT_PATH: ${{ github.workspace }}/artifacts/reports/sample_results.json
        run: |
          set -euxo pipefail
          echo "Using report: $REPORT_PATH"
          test -s "$REPORT_PATH"
          # If main.py takes a positional arg:
          python main.py "$REPORT_PATH"
          # If it needs a flag instead, use:
          # python main.py --report "$REPORT_PATH"
