name: AI Test Report Integration (Demo)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-noble  # match @playwright/test 1.56.x
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: List discovered tests (sanity)
        run: npx playwright test --list || true

      - name: Run Playwright Tests (HTML + JSON + LOG)
        run: |
          set -euxo pipefail
          REPORT_DIR="${{ runner.temp }}/playwright-report"
          mkdir -p "$REPORT_DIR"

          echo "Playwright CLI: $(npx playwright --version || true)"
          echo "Node: $(node -v)"
          echo "npm: $(npm -v)"

          JSON="${REPORT_DIR}/sample_results.json"
          RUNLOG="${REPORT_DIR}/playwright-run.log"

          # If not using the Playwright docker image, uncomment:
          # npx playwright install --with-deps

          # Execute tests, emit HTML and JSON, and tee a human-readable log
          npx playwright test \
            --reporter=html="${REPORT_DIR}",json="${JSON}" 2>&1 | tee "${RUNLOG}"

          # Validate JSON exists and is parseable
          test -s "${JSON}"
          node -e "JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'))" "${JSON}"

          # Copy JSON into repo dir for commit/artifact
          mkdir -p reports
          cp -f "${JSON}" reports/sample_results.json

      - name: Show report dir contents
        if: always()
        run: ls -la ${{ runner.temp }}/playwright-report || true

      - name: Upload Playwright JSON (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sample_results
          path: reports/sample_results.json

      - name: Upload Playwright LOG (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-run-log
          path: ${{ runner.temp }}/playwright-report/playwright-run.log

      - name: Upload Playwright HTML (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: ${{ runner.temp }}/playwright-report

      # --- Commit JSON back to the repo (only on branch runs, not PRs) ---
      - name: Commit JSON report to repo
        if: ${{ always() && github.event_name != 'pull_request' && startsWith(github.ref, 'refs/heads/') }}
        working-directory: ${{ github.workspace }}
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          CURRENT_BRANCH="${GITHUB_REF#refs/heads/}"
          git checkout "$CURRENT_BRANCH"
          git fetch origin "$CURRENT_BRANCH"
          git merge --ff-only "origin/$CURRENT_BRANCH" || true

          git add reports/sample_results.json
          git commit -m "Add Playwright JSON report for $GITHUB_SHA" || echo "No changes to commit"
          git push origin "HEAD:$CURRENT_BRANCH" || echo "Nothing to push"

  ai-agent:
    needs: e2e
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AI Agent Repository
        uses: actions/checkout@v4
        with:
          repository: azza-sudo/TestInsight-Agent
          path: testinsight

      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: sample_results
          path: testinsight

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install AI Agent Dependencies
        working-directory: testinsight
        run: pip install -r requirements.txt

      - name: Run AI Analysis
        working-directory: testinsight
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "Running TestInsight AI Agent..."
          python main.py sample_results.json

      - name: Upload AI Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-report
          path: testinsight/ai_report.json
